docs: update aspect compile
artela-network/artela-docs pull request #37
Opened 2024-01-17 11:01 UTC by gene-zhan

fix error Command

2024-01-17 11:02 UTC, luketheart approved these changes

2024-01-20 10:53 UTC, luketheart approved these changes
LGTM.

2024-01-20 11:04 UTC, dumbeng requested changes

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/guides/reentrancy-guard/index.md
> +                var oneCall = ethCallTree.calls.get(key);
oneCall -> parentCall

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/reference/aspect-lib/join-points/verify-aspect/index.md
> +> * 0xCAFECAFE serves as a stable value with a magical prefix.
stable value -> fixed vaue

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/reference/aspect-lib/join-points/verify-aspect/index.md
> +* 0xCAFECAFE75 is a magical prefix.
no 75 here

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/reference/aspect-lib/join-points/verify-aspect/index.md
> +* 75bac07d is 4-byte checksum of the encoded data.
Need to explain how to calculate the checksum

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/reference/aspect-lib/join-points/verify-aspect/index.md
> +* The remaining bytes represent the result of ABI encoding for ValidationData and CallData.
Need to explain how to encode the data

2024-01-20 11:04 UTC, dumbeng commented on docs/develop/reference/aspect-lib/join-points/verify-aspect/index.md
> +### Create customized verification transaction
This part is too long, the validation data constructed here is for session key, we need to provide a minimum case here.

2024-01-21 02:55 UTC, dumbeng approved these changes
LGTM

2024-01-21 03:09 UTC, merged